### ISSUE TITLE
Install outside of /apps/psp and /mnt/host_shared

### ISSUE THREAD

**Issue by nmb85** [algbioi/ppsp#1]
Are there instructions for instally phylopythiaS+ without root access?  I'd like to install it on our local university cluster, but I cannot because I do not have root access to install into the directories /apps or /mnt

**Comment by algbioi** [comment]
I would recommend to check with the administrator, whether it’s possible to install the VirtualBox on the server as it’s very convenient to run the software in the virtual machine. 

Alternatively, the directories /apps and /mnt are there for convenience to make it analogous to the VM installation. You can install all into a single directory (e.g. /home/username/pps). However, then you have to change all the paths in the configuration file, PATH and PYTHONPATH variables, and tools/ppsp and sys/update files accordingly. When calling the “update” commands, you have to call it as: “update -c tools.tar.xz:/home/username/pps” to get the latest scripts and as “update -c reference_NCBI20140513.tar.xz:home/username/pps” to get the reference. 

We are currently testing a distribution that removes all dependencies on ruby, which then substantially facilitates the installation, please check this website in a few weeks.

**Comment by nmb85** [comment]
Thank you!
