### ISSUE TITLE
Error in PPSP, not generating output files with sample example given in software

### ISSUE THREAD

**Issue by pandeyravi15** [algbioi/ppsp#3]
PPS "train" return code: 1
Traceback (most recent call last):
  File "/apps/pps/tools/ppsplus/algbioi/core/run.py", line 1008, in <module>
    main()
  File "/apps/pps/tools/ppsplus/algbioi/core/run.py", line 510, in main
    raise Exception("PPS train returned with non-zero %s status: %s" % (trainProc.returncode, trainCmd))
Exception: PPS train returned with non-zero 1 status: /mnt/apps/pps/tools/PhyloPythiaS/1_3/scripts/train.rb /apps/pps/tests/test02/working/PPS_config_generated.txt

**Comment by algbioi** [comment]
Thanks for your interest in using PPS+. This can only mean that 1) the installation was not successful (please make sure you performed all the installation steps) OR 2) You don't have enough resources (please make sure you have enough RAM and SWAP space. If you still cannot ran the example, please provide what operating system and hardware you have; along with all the log files.
