### ISSUE TITLE
Installing ppsp without VM and without root access

### ISSUE THREAD

**Issue by thkitapci** [algbioi/ppsp#4]
Hi, 
It says 

distribution (can be used to install PPS+ without VM)

I can't find instructions on how to install without VM. I am trying to install it on our computing cluster so I need to install without root access.

Thanks
Hamdi

**Comment by algbioi** [comment]
Dear Hamdi, Thank you for your interest in PPS+. I would strongly recommend to use the VM as it's easy to install and use. I would suggest to discuss the issue with your system administrator. If you still preferred to install PPS+ without VM, the instructions can be found here:
https://github.com/algbioi/ppsp/blob/master/Installation_instructions.pdf 
Section "Ubuntu PPS+ installation without VM".
