### ISSUE TITLE
Not generating all output files

### ISSUE THREAD

**Issue by vrbrand** [algbioi/ppsp#6]
Hi, 

I am running PhylopythiaS+ using the VM on a Mac, and the program is not generating the output files.  I had previously run both the example and a separate sample, and those had worked just fine, so I know the program installed correctly.  This time I get the following error:

```
PPS "train" return code: 0
Traceback (most recent call last):
  File "/apps/pps/tools/ppsplus/algbioi/core/run.py", line 1008, in <module>
    main()
  File "/apps/pps/tools/ppsplus/algbioi/core/run.py", line 552, in main
    shutil.move(str(fastaFileIds + '.nox.fna.out'), str(fastaFileIds + '.out'))
  File "/usr/lib/python2.7/shutil.py", line 299, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 128, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/apps/pps/tests/test072115/working/assembly24.fa.ids.nox.fna.out'
```
Sure enough, in the working directory, I get files like `assembly24.fa.ids.nox.fna.50000.sl`, but no `.out` files.  Is there a way to generate the output file from these files?  Do I have to re-run the program, and if so, what do I do differently to get the output file?  

Thanks so much for your help!

**Comment by algbioi** [comment]
Thanks for using PPS+. I would recommend to clean the working directory and check the input files for errors; and then re-run. Also make sure that you are not running out of disk space.
